crop-image-original/config/routes.rb
Imagecrop::Application.routes.draw do

  root :to => 'image#index'

  match "/images" => "image#index", :method=>:get, :as=>:images
  match "/image/create" => "image#create", :method=>:post, :as=>:create_image
  match "/image/show/:id" => "image#show", :method=>:get, :as=>:show_image
  match "/image/delete/:id" => "image#destroy", :method=>:delete, :as=>:delete_image

  match "/image/save" => "image#save" ,:method=>:post, :as=>:save_image
  match "file" => "image#file"

end

crop-image-original/app/models/asset.rb
# Author : Krishnaprasad Varma (kpvarma@presciencesoft.com)
# Date : 2 Jun, 2011
# All code (c)2011 Prescience Soft Pvt. Ltd. All rights reserved

class Asset < ActiveRecord::Base

  ## Set the table name
  set_table_name "assets"

  ## Specifies a white list of attributes that can be set via mass-assignment.
  attr_accessible :name, :content_type, :file_name, :document_file_name, :document_content_type, :document_file_size
  attr_accessible :document

  has_attached_file :document, :styles => { :tiny => "100x100>"},
    :url =>  "/public/uploaded_files/:style/:id.:extension",
    :path => ":rails_root/public/uploaded_files/:style/:id.:extension"

  validates_attachment_presence :document
  validates_attachment_size :document, :less_than => 5.megabytes
  validates_attachment_content_type :document, :content_type => ['application/txt', 'text/plain',
    'application/pdf', 'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.oasis.opendocument.text',
    'application/x-vnd.oasis.opendocument.text',
    'application/rtf', 'application/x-rtf', 'text/rtf', 'text/richtext', 'application/doc', 'application/x-soffice', 'image/jpg', 'image/jpeg', 'image/png']
  
end

crop-image-original/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

crop-image-original/app/controllers/image_controller.rb
class ImageController < ApplicationController


  def index

    @files = Asset.all
    @file = Asset.new

    respond_to do |format|
      format.html {}
      format.js { }
    end

  end

  def show

    @file = Asset.find(params[:id])

    respond_to do |format|
      format.html {}
      format.js { }
    end

  end

  def create

    @file = Asset.new(params[:asset])
    @file = Asset.new({:document=>params[:document]})
    @file.valid?
    unless params[:document]
      @file.errors.add(:document, "Invalid Image format, Unable to support images greater than 1MB")
    end

    @file.errors.add(:document,@file.errors[:document_file_name]) if @file.errors[:document_file_name].any?
    @file.errors.add(:document,@file.errors[:document_file_size]) if @file.errors[:document_file_size].any?
    @file.errors.add(:document,@file.errors[:document_file_type]) if @file.errors[:document_file_type].any?

    if @file.errors.empty?

      @file.save

      redirect_to images_path
   
    else

     

      flash[:notice] = "Upload a file"
      redirect_to images_path
 
    end

  end

  def destroy

    @file = Asset.find_by_id(params[:id])

    if @file
      @file.destroy
    end

    redirect_to images_path

  end
def save
  @fg = params["params"]
  

 @file = Asset.last
 @root= Rails.root.to_s
 @img = @file.document.to_s
 @img_path = @root + @img


@color = params["color"]



  @fg.each do |lis|
    
    val = lis[1]
 
     cord = val[0].to_s + 'x' + val[1].to_s + '+' + val[2].to_s + '+' + val[3].to_s
     if @color == '1'
          system "convert #{@img_path} -region #{cord} -fill black -colorize 100% #{@img_path}"
     elsif @color == '2'
          system "convert #{@img_path} -region #{cord} -fill white -colorize 100% #{@img_path}"
     elsif @color == '3'
          system "convert #{@img_path} -region #{cord} -fill blue -colorize 100% #{@img_path}"
     elsif @color == '4'
          system "convert #{@img_path} -region #{cord} -fill red -colorize 100% #{@img_path}"
     else
          system "convert #{@img_path} -region #{cord} -fill green -colorize 100% #{@img_path}"
     end
  end

end

end

crop-image-original/app/helpers/application_helper.rb
module ApplicationHelper
  def display_one_by_one(object, attribute, field, mandatory, label_text=nil, show_error=true)

    label_text = label_text || label(object, attribute)
    label_div = content_tag :div, label_text, :class=>"FLOAT_LEFT"
    error_div =  ""
    clear_5_tag = content_tag :div, "", :class=>"CL_5"
    if show_error && object.errors[attribute].any?
      error_div =  content_tag(:div, object.errors[attribute][0], :class=>"SHORT_ERROR_MSG")
      label_div = content_tag :div, label_text, :class=>"FLOAT_LEFT GRID_ERROR_LABEL"
    end

    if label_text == ""
      row_content = field + clear_5_tag + error_div + clear_5_tag
    else
      row_content = label_div + "#{mandatory ? ' *' : ''}" + clear_5_tag + field + clear_5_tag + error_div + clear_5_tag
    end

    return content_tag(:div, (row_content), :class=>"")

  end
end

crop-image-original/app/views/image/_form.html.erb
<div align="left">
  <h3 style="margin-left: 20px;"> Upload File </h3>
  <hr></hr>
  <br/>

  <% if @file %>
    <div id="DIV_IAMGE" style="width:105px;">
  <%#= image_tag(@file.url(:normal), :style=>"margin:0px;padding:0px", :width=>"150", :height=>"100") %>
    </div>
  <% end %>

  <div style="margin-left: 100px;width:50%;">

    <% path = create_image_path %>

    <%= form_tag(path, :method => :post,:multipart => true) do -%>

      <% field = file_field_tag "document", :style=>"height:22px;background-color:#FFF;color:#4B4B4B;padding: 2px;" %>
      <%= display_one_by_one(@file, :document, field, false, "")  %>

      <div style="clear:both;display: block;height: 10px;" ></div>

      <div style="float: right;margin-right: -45px;">
        <%= submit_tag "Save", :style=>"", :class => "BUTTON", :id=>"AVATAR" %>
      </div>
      <div style="clear:both;display: block;height: 10px;" ></div>
    <% end %>
  </div>
</div>

<%#*<iframe id='frame' name="FRAME_AVATAR" style="display:none;"></iframe>%>

crop-image-original/app/views/image/index.html.erb
<div style="clear:both;display: block;height: 10px;" ></div>
<div align="center" style="width:900px;">
  <div style="width:400px;background-color: #ffe599 ;border: solid 1px #eee;border-radius:4px;">
    <%= render :partial=>"form" %>
  </div>
</div>

<div style="clear:both;display: block;height: 10px;"></div>
<% @files.each do |file| %>
  <div style="padding: 5px;float: left;margin-left: 20px;display: block;border: 1px solid #0f5a96" >
    <%= image_tag "/uploaded_files/tiny/#{file.id}.jpg", :id => "target", :class=>"FLOAT_LEFT" %>
  </div>
  <div align="justify" id="DIV_IAMGE" style="float: left;width:614px;background-color: #FCFCFC;border: solid 1px #eee;padding: 10px;margin-left: 15px;font-family: arial;font-size: 14px;">
    <strong>Id :</strong> <%= id = file.id %><br/>
    <strong>Filename :</strong> <%= file.document_file_name %><br/>
    <strong>File path : </strong><%= file_path = file.document %><br/>
    <strong>Content type :</strong> <%= content_type = file.document_content_type %><br/>
    <strong>Item to hide file path : </strong><%= items_to_hide_file_path = "/home/prescience/items_to_hide.txt" %><br/>
    <strong>Bucket Name :</strong> <%= bucket_name = "s3resume" %><br/>
    <strong> Rails root :</strong> <%= rails_root_path = Rails.root.to_s %>
    <%= link_to "Delete", delete_image_path(:id=>file.id), :class => "BUTTON", :style=>"float:right;margin-left:10px;"  %>
    <%= link_to "Show", show_image_path(:id=>file.id), :class => "BUTTON", :style=>"float:right;"  %>
  </div>
  <div style="clear:both;display: block;height: 20px;" ></div>


		
<% end %>

crop-image-original/app/views/image/new.html.erb
<%
# Author : Krishnaprasad Varma (kpvarma@presciencesoft.com)
# Date : 30 May, 2011
# All code (c)2011 Prescience Soft Pvt. Ltd. All rights reserved
%>

<div style="width:400px;background-color: #f6f6f6;border: solid 1px #eee;">
  <%= render :partial=>"form" %>
</div>

crop-image-original/app/views/image/save.html.erb
<h1>post is working<h1>

crop-image-original/app/views/image/show.html.erb
<div class="CL"></div>
<div align="justify" id="DIV_IAMGE" style="float: left;width:614px;background-color: #ffe599 ;border: solid 1px #eee;padding: 10px;margin-left: 15px;font-family: arial;font-size: 14px;">
<h3>How to use : </h3>
<p><b>1 .</b>Select the portion of the image that you want to hid using image magic and then click add button,The selected cordinates will displayed above the image.</p>
<p><b>2 .</b>You can select multiple selections using jcrop,the only thing is that you have to click the add button after every selction ,then only the selected coordinates will be added to the array for hiding.</p>
<p><b>3 .</b>After you completed your selection,then press the desired color button that you wants to color with,now you you can see that the selected field is coloured with selected color.</p>
<%= link_to "Delete Image", delete_image_path(:id=>@file.id), :class => "BUTTON", :style=>"float:right;"  %>
</div>


<div id="X" style="float: left;width:614px;"></div>

<br/>


<div style="clear:both;display: block;height: 20px;" ></div>
<div style="padding: 5px;float: left;margin-left: 20px;display: block;border: 1px solid #0f5a96" >
  <%= image_tag "/uploaded_files/original/#{@file.id}.jpg", :id => "target" %>

</div>

<div style="clear:both;display: block;height: 20px;" ></div>
<div id="outer">
  <div class="jcExample">
    <div class="article">



      <!-- This is the image we're attaching Jcrop to -->


      <!-- This is the form that our event handler fills -->
      <form id="coords"
            class="coords"
            onsubmit="return false;"
            action="http://example.com/post.php">
        <div>
        <input type="hidden" size="4" id="x1" name="x1" />
           <input type="hidden" size="4" id="y1" name="y1" />
          <input type="hidden" size="4" id="x2" name="x2" />
          <input type="hidden" size="4" id="y2" name="y2" />
          <input type="hidden" size="4" id="w" name="w" />
        <input type="hidden" size="4" id="h" name="h" />

        </div>
        <button id="add" class ="BUTTON">ADD</button>
        <button id ="black" class ="BUTTON_1">BLACK</button>
<button id ="white" class ="BUTTON_2">WHITE</button>
<button id ="blue" class ="BUTTON_3" >BLUE</button>
<button id ="red" class ="BUTTON_4" >RED</button>
<button id ="green" class ="BUTTON_5">GREEN</button>
      </form>
      <div style="clear:both;display: block;height: 5px;" ></div>
      <div id="outer">
        <div class="jcExample">
          <div class="article">
            <div id="interface" style="margin: 1em 0;"></div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style type="text/css">
  .inline_div {
      background-color: #FCFCFC;
      border: solid 1px #EEE;
      margin: 10px;
      padding: 10px;
  }
</style>

<script type="text/javascript">
  jQuery(function($){

    $('#target').Jcrop({
      onChange:   showCoords,
      onSelect:   showCoords,
      onRelease:  clearCoords
    });

  });
  function showCoords(c)
  {
    $('#x1').val(c.x);
    $('#y1').val(c.y);
    $('#x2').val(c.x2);
    $('#y2').val(c.y2);
    $('#w').val(c.w);
    $('#h').val(c.h);
  };

  function clearCoords()
  {
    $('#coords input').val('');
    $('#h').css({color:'red'});
    window.setTimeout(function(){
      $('#h').css({color:'inherit'});
    },500);
  };

</script>
<script type="text/javascript">
      var i =1;
      var j =1;
     
      var adj_list=[];
  jQuery(document).ready(function(){
    jQuery("#add").click(function(){
      var cord_list=[];
      
      var X1 = jQuery("#x1").val();
      var Y1 = jQuery("#y1").val();
      var X2 = jQuery("#x2").val();
      var Y2 = jQuery("#y2").val();
      var W = jQuery("#w").val();
      var H = jQuery("#h").val();
      cord_list= [W,H,X1,Y1];
      //alert(cord_list);
      adj_list.push(cord_list);
      //alert(adj_list);
      //alert(X1);
      jQuery('<div/>', {
    	'id': 'X',
        'class': 'inline_div',
    	'rel': 'external',
    	'text': "X1 : "+X1+" , "+"Y1 : "+Y1+" , "+"X2 : "+X2+" , "+"Y2 : "+Y2 +" , "+"Height : "+H+" , "+"Width : "+W
		}).appendTo('#X');

      jQuery('#X').append($(o));
	//i=i+1;
        
        j=j+1;
    });

    //var datastring = adj_list+'&authenticity_token='+AUTH_TOKEN;
    //var val = encodeURIComponent(JSON.stringify(adj_list));
    var val=adj_list;
         jQuery("#black").click(function(){
         jQuery.ajax({
            type: "POST",
            url: "/image/save",
            data: {"params": val,"color": 1},
            complete: function () {
        window.location.reload(true);
    }
         });});


         jQuery("#white").click(function(){
         jQuery.ajax({
            type: "POST",
            url: "/image/save",
            data: {"params": val,"color": 2},
            complete: function () {
        window.location.reload(true);
    }
     });});
         jQuery("#blue").click(function(){
         jQuery.ajax({
            type: "POST",
            url: "/image/save",
            data: {"params": val,"color": 3},
            complete: function () {
        window.location.reload(true);
    }
     });});
         jQuery("#red").click(function(){
         jQuery.ajax({
            type: "POST",
            url: "/image/save",
            data: {"params": val,"color": 4},
            complete: function () {
        window.location.reload(true);
    }
    });});
    var val=adj_list;
         jQuery("#green").click(function(){
         jQuery.ajax({
            type: "POST",
            url: "/image/save",
            data: {"params": val,"color": 5},
            complete: function () {
        window.location.reload(true);
    }
});
  });


      
 

       });
  

</script>





  

crop-image-original/app/views/layouts/_footer.erb
<div class="FOOTER">
	<center><h5 style="color:white ;margin: 5px 0px;">Copyright sreehari@presciencesoft.com</h5></center>
</div>

crop-image-original/app/views/layouts/_header.erb
<div class="HEADER">
	<center><h1 style="color:#990000;margin: 5px 0px;">Rails Project - Image hiding using jcrop & Imagemagic </h1></center>
	<div class="SHELL">
		<div class="FLOAT_LEFT">
			<%= link_to "Home", root_path ,:class=> "BUTTON" %>
	    </div>
		<div class="FLOAT_RIGHT">
		
		</div>
	</div>
</div>

crop-image-original/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imagecrop</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<body>
	<%= render :partial=>"/layouts/header" %>
	
	<div class="SHELL">
		
		<div class="CL"></div>
		<%= yield %>
		<div class="CL"></div>
	</div>
	
	<%= render :partial=>"/layouts/footer" %>

</body>

</body>
</html>